name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create file name
        id: get_file_name
        run: |
          echo "FN=aisteroids-${{ github.ref_name }}.love" >> $GITHUB_OUTPUT

      - name: Create .love file
        run: |
          zip -9 -r ${{ steps.get_file_name.outputs.FN }} . -x ".*"

      - name: Upload .love file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_file_name.outputs.FN }}
          path: ${{ steps.get_file_name.outputs.FN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.get_file_name.outputs.FN }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
